spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
logging:
  level:
    logging:
      level:
        root: INFO
        org.springframework.amqp.rabbit.connection: DEBUG
